name: 'Music'

on:
  push:
    branches:
    - main
  schedule:
    - cron: '30 04 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7
      - name: Setting
        run: |
          if [ '${{ secrets.USERNAME }}' != '' ]; then sed -i 's/"username": ""/"username": ""${{ secrets.USERNAME }}""/' config.json; fi
          if [ '${{ secrets.PASSWORD }}' != '' ]; then sed -i 's/"password": ""/"username": ""${{ secrets.PASSWORD }}""/' config.json; fi
          if [ '${{ secrets.COOKIE }}' != '' ]; then sed -i 's/"cookie": ""/"cookie": ""${{ secrets.MULTIPLE_ACCOUNTS }}""/' config.json; fi

      - name: requirements
        run : pip3 install -r requirements.txt
      
      - name: 网易云音乐
        run: |
          python3 index.py
