name: 'Music'

on:
  push:
    branches:
    - main
  schedule:
    - cron: '30 04 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7
               
      - name: requirements
        run : pip3 install -r requirements.txt
      
      - name: 网易云音乐
        run: |
          python3 index.py
