name: 'Music'

on:
  push:
    branches:
    - main
  schedule:
    - cron: '30 04 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7
          

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          
      - name: requirements
        run : pip3 install -r requirements.txt
      
      - name: Setting
        run: |

          if [ '${{ secrets.username }}' != '' ]; then sed -i "s/^username=.*$/username='${{ secrets.username }}'/" config.json; fi
          if [ '${{ secrets.password }}' != '' ]; then sed -i "s/^password=.*$/password='${{ secrets.password }}'/" config.json; fi
          if [ '${{ secrets.cookie }}' != '' ]; then sed -i "s/^cookie=.*$/cookie='${{ secrets.cookie }}'/" config.json; fi
          if [ '${{ secrets.pushToken }}' != '' ]; then sed -i "s/^pushToken=.*$/pushToken='${{ secrets.pushToken }}'/" config.json; fi
          if [ '${{ secrets.enable }}' != '' ]; then sed -i "s/^enable=.*$/enable='${{ secrets.enable }}'/" config.json; fi
          if [ '${{ secrets.follow }}' != '' ]; then sed -i "s/^follow=.*$/follow='${{ secrets.follow }}'/" config.json; fi
      - name: 网易云音乐
        run: |
          python3 index.py
