name: 'Music'

on:
  push:
    branches:
    - main
  schedule:
    - cron: '30 04 * * *'
  workflow_dispatch:
env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  COOKIE: ${{ secrets.COOKIE }}
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7
      - name: Setting
        run: |
          cat>config.json<<-\EOF
            "username": "$USERNAME"
            "password": "$PASSWORD"
            "cookie": "$COOKIE"
          EOF
      - name: requirements
        run : pip3 install -r requirements.txt
      
      - name: 网易云音乐
        run: |
          python3 index.py
